version: '3.7'

services:
  task_manager:
    build: 
      context: .
    volumes:
      - static_data:/task_Manager/staticfiles
      - "./dist/media:/task_Manager/media" #map to local machine
    env_file: # if .env in root, we have to show .env here must
      - ./.env  
    depends_on: 
      - db

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/task_Manager/staticfiles
      - "./dist/media:/task_Manager/media" # map to local machine
    ports:
      - "80:80"
    env_file: # if .env in root,  we have to show .env here must
      - ./.env
    depends_on:
      - task_manager
      - db

  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/database
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432" 

volumes:
  static_data:
  database:
