# Generated by Django 5.0.2 on 2024-02-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='categrory',
            new_name='category',
        ),
    ]
